package POJO;
// Generated 12-feb-2016 13:14:56 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private Direccion direccion;
     private String nombre;
     private String apellidos;

    public Persona() {
    }

	
    public Persona(Direccion direccion) {
        this.direccion = direccion;
    }
    public Persona(Direccion direccion, String nombre, String apellidos) {
       this.direccion = direccion;
       this.nombre = nombre;
       this.apellidos = apellidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Override
    public String toString() {
        return "Persona{" + "id=" + id + ", direccion=" + direccion + ", nombre=" + nombre + ", apellidos=" + apellidos + '}';
    }




}


