package POJO;
// Generated 22-feb-2016 12:29:51 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private Direccion direccion;
     private String nombre;
     private String apellidos;
     private String nif;

    public Persona() {
    }

	
    public Persona(Direccion direccion) {
        this.direccion = direccion;
    }
    public Persona(Direccion direccion, String nombre, String apellidos, String nif) {
       this.direccion = direccion;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.nif = nif;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }




}


